// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuhhdcswnwqlrhawnxlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aGhkY3N3bndxbHJoYXdueGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODQ3OTEsImV4cCI6MjA2NTc2MDc5MX0.Wytqd7Jd4w70HEUn32-vNTF1QNooZ2-olDzHSQUR5kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);